import 'package:p2d_flutter/core/constants/app_constants.dart';

class OrderModel {
  final String id;
  final String customerId;
  final String? driverId;
  final String pickupAddress;
  final double pickupLat;
  final double pickupLng;
  final String dropAddress;
  final double dropLat;
  final double dropLng;
  final String? itemDescription;
  final double? itemWeight;
  final String status;
  final String? pickupOtp;
  final String? deliveryOtp;
  final String? pickupQrToken;
  final String? deliveryQrToken;
  final double estimatedPrice;
  final double? finalPrice;
  final bool insuranceEnabled;
  final double? insuranceAmount;
  final String paymentStatus;
  final String? razorpayOrderId;
  final DateTime createdAt;
  final DateTime? pickedUpAt;
  final DateTime? deliveredAt;

  OrderModel({
    required this.id,
    required this.customerId,
    this.driverId,
    required this.pickupAddress,
    required this.pickupLat,
    required this.pickupLng,
    required this.dropAddress,
    required this.dropLat,
    required this.dropLng,
    this.itemDescription,
    this.itemWeight,
    required this.status,
    this.pickupOtp,
    this.deliveryOtp,
    this.pickupQrToken,
    this.deliveryQrToken,
    required this.estimatedPrice,
    this.finalPrice,
    required this.insuranceEnabled,
    this.insuranceAmount,
    required this.paymentStatus,
    this.razorpayOrderId,
    required this.createdAt,
    this.pickedUpAt,
    this.deliveredAt,
  });

  factory OrderModel.fromJson(Map<String, dynamic> json) {
    return OrderModel(
      id: json['id'] as String,
      customerId: json['customer_id'] as String,
      driverId: json['driver_id'] as String?,
      pickupAddress: json['pickup_address'] as String,
      pickupLat: (json['pickup_lat'] as num).toDouble(),
      pickupLng: (json['pickup_lng'] as num).toDouble(),
      dropAddress: json['drop_address'] as String,
      dropLat: (json['drop_lat'] as num).toDouble(),
      dropLng: (json['drop_lng'] as num).toDouble(),
      itemDescription: json['item_description'] as String?,
      itemWeight: (json['item_weight'] as num?)?.toDouble(),
      status: json['status'] as String,
      pickupOtp: json['pickup_otp'] as String?,
      deliveryOtp: json['delivery_otp'] as String?,
      pickupQrToken: json['pickup_qr_token'] as String?,
      deliveryQrToken: json['delivery_qr_token'] as String?,
      estimatedPrice: (json['estimated_price'] as num).toDouble(),
      finalPrice: (json['final_price'] as num?)?.toDouble(),
      insuranceEnabled: json['insurance_enabled'] as bool? ?? false,
      insuranceAmount: (json['insurance_amount'] as num?)?.toDouble(),
      paymentStatus: json['payment_status'] as String,
      razorpayOrderId: json['razorpay_order_id'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
      pickedUpAt: json['picked_up_at'] != null ? DateTime.parse(json['picked_up_at']) : null,
      deliveredAt: json['delivered_at'] != null ? DateTime.parse(json['delivered_at']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    // Note: This might not be used for creating orders, as backend handles price/OTP.
    // Primarily for sending order data to backend or for local state.
    return {
      'id': id,
      'customer_id': customerId,
      'driver_id': driverId,
      'pickup_address': pickupAddress,
      'pickup_lat': pickupLat,
      'pickup_lng': pickupLng,
      'drop_address': dropAddress,
      'drop_lat': dropLat,
      'drop_lng': dropLng,
      'item_description': itemDescription,
      'item_weight': itemWeight,
      'status': status,
      // OTPs, QR tokens are generated by backend. Do not include here for POST requests.
      'estimated_price': estimatedPrice,
      'final_price': finalPrice,
      'insurance_enabled': insuranceEnabled,
      'insurance_amount': insuranceAmount,
      'payment_status': paymentStatus,
      'razorpay_order_id': razorpayOrderId,
      'created_at': createdAt.toIso8601String(),
      'picked_up_at': pickedUpAt?.toIso8601String(),
      'delivered_at': deliveredAt?.toIso8601String(),
    };
  }
}
